/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_reclam (void);
GtkWidget* create_ajout_reclam (void);
GtkWidget* create_recherche_reclam (void);
GtkWidget* create_afficher_reclam (void);
GtkWidget* create_recherchef_reclam (void);
GtkWidget* create_modif_reclam (void);
