/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_reclam (void)
{
  GtkWidget *gestion_reclam;
  GtkWidget *fixed1;
  GtkWidget *image5;
  GtkWidget *image7;
  GtkWidget *image6;
  GtkWidget *recherche_reclam;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *modifier_reclam;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *ajouter_reclam;
  GtkWidget *afficher_reclam;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *supprimer_reclam;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;

  gestion_reclam = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_reclam), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestion_reclam), fixed1);

  image5 = create_pixmap (gestion_reclam, "k.jpg");
  gtk_widget_show (image5);
  gtk_fixed_put (GTK_FIXED (fixed1), image5, 40, 168);
  gtk_widget_set_size_request (image5, 152, 168);

  image7 = create_pixmap (gestion_reclam, "m.jpg");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed1), image7, 488, 168);
  gtk_widget_set_size_request (image7, 152, 176);

  image6 = create_pixmap (gestion_reclam, "u.png");
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed1), image6, 240, 232);
  gtk_widget_set_size_request (image6, 224, 216);

  recherche_reclam = gtk_button_new ();
  gtk_widget_show (recherche_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), recherche_reclam, 496, 368);
  gtk_widget_set_size_request (recherche_reclam, 130, 93);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (recherche_reclam), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("rechercher\nreclamation"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  modifier_reclam = gtk_button_new ();
  gtk_widget_show (modifier_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), modifier_reclam, 504, 32);
  gtk_widget_set_size_request (modifier_reclam, 130, 96);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (modifier_reclam), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-cut", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("modifier\nreclamation"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  ajouter_reclam = gtk_button_new_with_mnemonic (_("ajouter\nreclamation"));
  gtk_widget_show (ajouter_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter_reclam, 272, 72);
  gtk_widget_set_size_request (ajouter_reclam, 144, 88);

  afficher_reclam = gtk_button_new ();
  gtk_widget_show (afficher_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher_reclam, 32, 32);
  gtk_widget_set_size_request (afficher_reclam, 144, 96);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (afficher_reclam), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("afficher\nreclamation"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  supprimer_reclam = gtk_button_new ();
  gtk_widget_show (supprimer_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), supprimer_reclam, 48, 360);
  gtk_widget_set_size_request (supprimer_reclam, 136, 96);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (supprimer_reclam), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("supprimer\nreclamation"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) recherche_reclam, "clicked",
                    G_CALLBACK (on_recherche_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_reclam, "clicked",
                    G_CALLBACK (on_modifier_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_reclam, "clicked",
                    G_CALLBACK (on_ajouter_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher_reclam, "clicked",
                    G_CALLBACK (on_afficher_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_reclam, "clicked",
                    G_CALLBACK (on_supprimer_reclam_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_reclam, gestion_reclam, "gestion_reclam");
  GLADE_HOOKUP_OBJECT (gestion_reclam, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestion_reclam, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_reclam, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_reclam, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_reclam, recherche_reclam, "recherche_reclam");
  GLADE_HOOKUP_OBJECT (gestion_reclam, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_reclam, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_reclam, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_reclam, label3, "label3");
  GLADE_HOOKUP_OBJECT (gestion_reclam, modifier_reclam, "modifier_reclam");
  GLADE_HOOKUP_OBJECT (gestion_reclam, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion_reclam, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion_reclam, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestion_reclam, label2, "label2");
  GLADE_HOOKUP_OBJECT (gestion_reclam, ajouter_reclam, "ajouter_reclam");
  GLADE_HOOKUP_OBJECT (gestion_reclam, afficher_reclam, "afficher_reclam");
  GLADE_HOOKUP_OBJECT (gestion_reclam, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gestion_reclam, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gestion_reclam, image1, "image1");
  GLADE_HOOKUP_OBJECT (gestion_reclam, label1, "label1");
  GLADE_HOOKUP_OBJECT (gestion_reclam, supprimer_reclam, "supprimer_reclam");
  GLADE_HOOKUP_OBJECT (gestion_reclam, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_reclam, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_reclam, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_reclam, label4, "label4");

  return gestion_reclam;
}

GtkWidget*
create_ajout_reclam (void)
{
  GtkWidget *ajout_reclam;
  GtkWidget *fixed2;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *add_reclam;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label10;
  GtkWidget *button2;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image8;
  GtkWidget *label9;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *radiobutton8;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton1;
  GtkWidget *radiobutton5;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *termes;
  GtkWidget *label11;

  ajout_reclam = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_reclam), _("window1"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajout_reclam), fixed2);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 360, 40);
  gtk_widget_set_size_request (entry1, 272, 152);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 40, 248);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label7 = gtk_label_new (_("bureau de vote a reclamer"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 32, 296);
  gtk_widget_set_size_request (label7, 288, 33);

  label8 = gtk_label_new (_("liste electorale a reclamer"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 56, 424);
  gtk_widget_set_size_request (label8, 272, 40);

  add_reclam = gtk_button_new ();
  gtk_widget_show (add_reclam);
  gtk_fixed_put (GTK_FIXED (fixed2), add_reclam, 496, 272);
  gtk_widget_set_size_request (add_reclam, 112, 64);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (add_reclam), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("envoyer"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox6), label10, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed2), button2, 496, 352);
  gtk_widget_set_size_request (button2, 104, 64);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button2), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox5), image8, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox5), label9, FALSE, FALSE, 0);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("3"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton7, 200, 488);
  gtk_widget_set_size_request (radiobutton7, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("4"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton8, 304, 488);
  gtk_widget_set_size_request (radiobutton8, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("4"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton4, 304, 368);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("3"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton3, 192, 368);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("2"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2, 112, 368);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("2"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton6, 104, 488);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("1"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1, 24, 368);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("1"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton5, 24, 488);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  label5 = gtk_label_new (_("votre reclamation :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 72, 104);
  gtk_widget_set_size_request (label5, 256, 48);

  label6 = gtk_label_new (_("id:"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 56, 208);
  gtk_widget_set_size_request (label6, 41, 17);

  termes = gtk_check_button_new_with_mnemonic (_("j'ai lu et accepte les termes et conditions "));
  gtk_widget_show (termes);
  gtk_fixed_put (GTK_FIXED (fixed2), termes, 24, 40);
  gtk_widget_set_size_request (termes, 304, 56);

  label11 = gtk_label_new ("");
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 424, 480);
  gtk_widget_set_size_request (label11, 241, 57);

  g_signal_connect ((gpointer) add_reclam, "clicked",
                    G_CALLBACK (on_add_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton7, "toggled",
                    G_CALLBACK (on_radiobutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton8, "toggled",
                    G_CALLBACK (on_radiobutton8_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6, "toggled",
                    G_CALLBACK (on_radiobutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) termes, "toggled",
                    G_CALLBACK (on_termes_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_reclam, ajout_reclam, "ajout_reclam");
  GLADE_HOOKUP_OBJECT (ajout_reclam, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajout_reclam, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (ajout_reclam, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (ajout_reclam, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajout_reclam, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajout_reclam, add_reclam, "add_reclam");
  GLADE_HOOKUP_OBJECT (ajout_reclam, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ajout_reclam, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajout_reclam, image9, "image9");
  GLADE_HOOKUP_OBJECT (ajout_reclam, label10, "label10");
  GLADE_HOOKUP_OBJECT (ajout_reclam, button2, "button2");
  GLADE_HOOKUP_OBJECT (ajout_reclam, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (ajout_reclam, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ajout_reclam, image8, "image8");
  GLADE_HOOKUP_OBJECT (ajout_reclam, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajout_reclam, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (ajout_reclam, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (ajout_reclam, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (ajout_reclam, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (ajout_reclam, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (ajout_reclam, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (ajout_reclam, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (ajout_reclam, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (ajout_reclam, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajout_reclam, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajout_reclam, termes, "termes");
  GLADE_HOOKUP_OBJECT (ajout_reclam, label11, "label11");

  return ajout_reclam;
}

GtkWidget*
create_recherche_reclam (void)
{
  GtkWidget *recherche_reclam;
  GtkWidget *fixed3;
  GtkWidget *label12;
  GtkWidget *entry3;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *recherche1_reclam;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label13;

  recherche_reclam = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (recherche_reclam), _("window1"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (recherche_reclam), fixed3);

  label12 = gtk_label_new (_("donner l'id:"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 216, 128);
  gtk_widget_set_size_request (label12, 184, 72);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 192, 208);
  gtk_widget_set_size_request (entry3, 240, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  button4 = gtk_button_new_with_mnemonic (_("accueil"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed3), button4, 56, 48);
  gtk_widget_set_size_request (button4, 96, 48);

  button5 = gtk_button_new_with_mnemonic (_("administration"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed3), button5, 200, 40);
  gtk_widget_set_size_request (button5, 128, 64);

  button6 = gtk_button_new_with_mnemonic (_("profil"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed3), button6, 376, 40);
  gtk_widget_set_size_request (button6, 96, 56);

  button7 = gtk_button_new_with_mnemonic (_("se deconnecter"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed3), button7, 512, 48);
  gtk_widget_set_size_request (button7, 120, 48);

  recherche1_reclam = gtk_button_new ();
  gtk_widget_show (recherche1_reclam);
  gtk_fixed_put (GTK_FIXED (fixed3), recherche1_reclam, 240, 328);
  gtk_widget_set_size_request (recherche1_reclam, 144, 80);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (recherche1_reclam), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("rechercher\nreclamation"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox7), label13, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) recherche1_reclam, "clicked",
                    G_CALLBACK (on_recherche1_reclam_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (recherche_reclam, recherche_reclam, "recherche_reclam");
  GLADE_HOOKUP_OBJECT (recherche_reclam, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (recherche_reclam, label12, "label12");
  GLADE_HOOKUP_OBJECT (recherche_reclam, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (recherche_reclam, button4, "button4");
  GLADE_HOOKUP_OBJECT (recherche_reclam, button5, "button5");
  GLADE_HOOKUP_OBJECT (recherche_reclam, button6, "button6");
  GLADE_HOOKUP_OBJECT (recherche_reclam, button7, "button7");
  GLADE_HOOKUP_OBJECT (recherche_reclam, recherche1_reclam, "recherche1_reclam");
  GLADE_HOOKUP_OBJECT (recherche_reclam, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (recherche_reclam, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (recherche_reclam, image10, "image10");
  GLADE_HOOKUP_OBJECT (recherche_reclam, label13, "label13");

  return recherche_reclam;
}

GtkWidget*
create_afficher_reclam (void)
{
  GtkWidget *afficher_reclam;
  GtkWidget *fixed4;
  GtkWidget *treeview_afficher_reclam;
  GtkWidget *button9;
  GtkWidget *button10;
  GtkWidget *button11;
  GtkWidget *button12;
  GtkWidget *retour_afficher_reclam;

  afficher_reclam = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (afficher_reclam), _("window1"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (afficher_reclam), fixed4);

  treeview_afficher_reclam = gtk_tree_view_new ();
  gtk_widget_show (treeview_afficher_reclam);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview_afficher_reclam, 112, 128);
  gtk_widget_set_size_request (treeview_afficher_reclam, 440, 200);

  button9 = gtk_button_new_with_mnemonic (_("accueil"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed4), button9, 56, 48);
  gtk_widget_set_size_request (button9, 96, 48);

  button10 = gtk_button_new_with_mnemonic (_("administration"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed4), button10, 200, 40);
  gtk_widget_set_size_request (button10, 128, 64);

  button11 = gtk_button_new_with_mnemonic (_("profil"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed4), button11, 376, 40);
  gtk_widget_set_size_request (button11, 96, 56);

  button12 = gtk_button_new_with_mnemonic (_("se deconnecter"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed4), button12, 512, 48);
  gtk_widget_set_size_request (button12, 120, 48);

  retour_afficher_reclam = gtk_button_new_with_mnemonic (_("retourner "));
  gtk_widget_show (retour_afficher_reclam);
  gtk_fixed_put (GTK_FIXED (fixed4), retour_afficher_reclam, 264, 360);
  gtk_widget_set_size_request (retour_afficher_reclam, 152, 88);

  g_signal_connect ((gpointer) treeview_afficher_reclam, "row_activated",
                    G_CALLBACK (on_treeview_afficher_reclam_row_activated),
                    NULL);
  g_signal_connect ((gpointer) retour_afficher_reclam, "clicked",
                    G_CALLBACK (on_retour_afficher_reclam_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficher_reclam, afficher_reclam, "afficher_reclam");
  GLADE_HOOKUP_OBJECT (afficher_reclam, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (afficher_reclam, treeview_afficher_reclam, "treeview_afficher_reclam");
  GLADE_HOOKUP_OBJECT (afficher_reclam, button9, "button9");
  GLADE_HOOKUP_OBJECT (afficher_reclam, button10, "button10");
  GLADE_HOOKUP_OBJECT (afficher_reclam, button11, "button11");
  GLADE_HOOKUP_OBJECT (afficher_reclam, button12, "button12");
  GLADE_HOOKUP_OBJECT (afficher_reclam, retour_afficher_reclam, "retour_afficher_reclam");

  return afficher_reclam;
}

GtkWidget*
create_recherchef_reclam (void)
{
  GtkWidget *recherchef_reclam;
  GtkWidget *fixed5;
  GtkWidget *button13;
  GtkWidget *button14;
  GtkWidget *button15;
  GtkWidget *button16;
  GtkWidget *treeview_recherche_reclam;

  recherchef_reclam = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (recherchef_reclam), _("window2"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (recherchef_reclam), fixed5);

  button13 = gtk_button_new_with_mnemonic (_("accueil"));
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed5), button13, 56, 48);
  gtk_widget_set_size_request (button13, 96, 48);

  button14 = gtk_button_new_with_mnemonic (_("administration"));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed5), button14, 200, 40);
  gtk_widget_set_size_request (button14, 128, 64);

  button15 = gtk_button_new_with_mnemonic (_("profil"));
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed5), button15, 376, 40);
  gtk_widget_set_size_request (button15, 96, 56);

  button16 = gtk_button_new_with_mnemonic (_("se deconnecter"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed5), button16, 512, 48);
  gtk_widget_set_size_request (button16, 120, 48);

  treeview_recherche_reclam = gtk_tree_view_new ();
  gtk_widget_show (treeview_recherche_reclam);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview_recherche_reclam, 176, 176);
  gtk_widget_set_size_request (treeview_recherche_reclam, 300, 200);

  g_signal_connect ((gpointer) treeview_recherche_reclam, "row_activated",
                    G_CALLBACK (on_treeview_recherche_reclam_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (recherchef_reclam, recherchef_reclam, "recherchef_reclam");
  GLADE_HOOKUP_OBJECT (recherchef_reclam, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (recherchef_reclam, button13, "button13");
  GLADE_HOOKUP_OBJECT (recherchef_reclam, button14, "button14");
  GLADE_HOOKUP_OBJECT (recherchef_reclam, button15, "button15");
  GLADE_HOOKUP_OBJECT (recherchef_reclam, button16, "button16");
  GLADE_HOOKUP_OBJECT (recherchef_reclam, treeview_recherche_reclam, "treeview_recherche_reclam");

  return recherchef_reclam;
}

GtkWidget*
create_modif_reclam (void)
{
  GtkWidget *modif_reclam;
  GtkWidget *fixed6;
  GtkWidget *label14;
  GtkWidget *combobox1;
  GtkWidget *label15;
  GtkWidget *combobox2;
  GtkWidget *label16;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *label17;
  GtkWidget *modifier_reclamation;
  GtkWidget *label18;

  modif_reclam = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modif_reclam), _("window3"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (modif_reclam), fixed6);

  label14 = gtk_label_new (_("bureau de vote "));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed6), label14, 24, 16);
  gtk_widget_set_size_request (label14, 168, 56);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox1, 72, 72);
  gtk_widget_set_size_request (combobox1, 72, 72);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("4"));

  label15 = gtk_label_new (_("liste electorale"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed6), label15, 32, 168);
  gtk_widget_set_size_request (label15, 160, 48);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox2, 80, 232);
  gtk_widget_set_size_request (combobox2, 72, 72);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("4"));

  label16 = gtk_label_new (_("id :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed6), label16, 376, 24);
  gtk_widget_set_size_request (label16, 49, 17);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed6), entry4, 344, 72);
  gtk_widget_set_size_request (entry4, 168, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed6), entry5, 240, 200);
  gtk_widget_set_size_request (entry5, 248, 232);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label17 = gtk_label_new (_("reclamation modifiee"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed6), label17, 248, 136);
  gtk_widget_set_size_request (label17, 192, 64);

  modifier_reclamation = gtk_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (modifier_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed6), modifier_reclamation, 544, 336);
  gtk_widget_set_size_request (modifier_reclamation, 176, 104);

  label18 = gtk_label_new ("");
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed6), label18, 584, 104);
  gtk_widget_set_size_request (label18, 160, 168);

  g_signal_connect ((gpointer) modifier_reclamation, "clicked",
                    G_CALLBACK (on_modifier_reclamation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif_reclam, modif_reclam, "modif_reclam");
  GLADE_HOOKUP_OBJECT (modif_reclam, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (modif_reclam, label14, "label14");
  GLADE_HOOKUP_OBJECT (modif_reclam, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (modif_reclam, label15, "label15");
  GLADE_HOOKUP_OBJECT (modif_reclam, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (modif_reclam, label16, "label16");
  GLADE_HOOKUP_OBJECT (modif_reclam, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (modif_reclam, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (modif_reclam, label17, "label17");
  GLADE_HOOKUP_OBJECT (modif_reclam, modifier_reclamation, "modifier_reclamation");
  GLADE_HOOKUP_OBJECT (modif_reclam, label18, "label18");

  return modif_reclam;
}

