/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *gestion_reclam;
  GtkWidget *ajout_reclam;
  GtkWidget *recherche_reclam;
  GtkWidget *afficher_reclam;
  GtkWidget *recherchef_reclam;
  GtkWidget *modif_reclam;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
 gestion_reclam = create_gestion_reclam ();
  gtk_widget_show (gestion_reclam);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 
  /*ajout_reclam = create_ajout_reclam ();
  gtk_widget_show (ajout_reclam);
  recherche_reclam = create_recherche_reclam ();
  gtk_widget_show (recherche_reclam);
  afficher_reclam = create_afficher_reclam ();
  gtk_widget_show (afficher_reclam);
  recherchef_reclam = create_recherchef_reclam ();
  gtk_widget_show (recherchef_reclam);
  modif_reclam = create_modif_reclam ();
  gtk_widget_show (modif_reclam); */

  gtk_main ();
  return 0;
}

